name: "Mathlib style linter"
description: |
  Text-based linters to ensure Lean code meets Mathlib style guidelines.
  This action will automatically make suggestions to PRs to fix style issues.
  Write "bot fix style" in a comment to have a bot apply all style suggestions.

  This action is intended to run in two workflows, with different `mode` settings.
  * on `pull_request`, run this action in mode `suggest` to run the linters and comment with suggestions.
  * on `issue_comment`, `pull_request_review` or `pull_request_review_comment` (with types `[created, edited`),
    run this action in mode `fix` to listen for "bot fix style" comments and apply the suggestions.

inputs:
  mode:
    description: |
      The actions taken based on style linter output.
      When set to `suggest`, this action adds review comments with suggestions.
      When set to `fix`, this action looks for a "bot fix style" comment and pushes a commit with the suggested fixes.
      Allowed values: "suggest" or "fix".
    required: true
  lint-bib-file:
    description: |
      Enables linting of the bibiliography using `./scripts/lint-bib.sh`.
    required: false
    default: "false"

outputs:
  user_permission:
    description: |
      (In `fix` mode:) Did the user ask for "bot fix style" and have enough permission?
      Allowed values: "true" | "false"
    value: ${{ steps.user_permission.outputs.require-result }}

runs:
  using: "composite"
  steps:
    - name: Find bot fix style
      if: ${{ inputs.mode == 'fix' }}
      id: bot_fix_style
      run: |
        COMMENT="${COMMENT_EVENT}${COMMENT_REVIEW}${COMMENT_REVIEW_COMMENT}"
        # we strip `\r` since line endings from GitHub contain this character
        COMMENT="${COMMENT//$'\r'/}"
        # for debugging, we print some information
        printf '%s' "${COMMENT}" | hexdump -cC
        printf 'Comment:"%s"\n' "${COMMENT}"
        bot_fix_style="$(printf '%s' "${COMMENT}" |
          sed -n 's=^bot fix style$=bot-fix-style=p' | head -1)"

        printf $'"bot fix style"? \'%s\'\n' "${bot_fix_style}"
        printf $'AUTHOR: \'%s\'\n' "${AUTHOR}"
        printf $'PR_NUMBER: \'%s\'\n' "${{ github.event.issue.number }}${{ github.event.pull_request.number }}"
        printf $'%s' "${{ github.event.issue.number }}${{ github.event.pull_request.number }}" | hexdump -cC

        printf $'bot_fix_style=%s\n' "${bot_fix_style}" >> "${GITHUB_OUTPUT}"
        # these final variables are probably not relevant for the bot_fix_style action
        if [ "${AUTHOR}" == 'leanprover-community-mathlib4-bot' ] ||
           [ "${AUTHOR}" == 'leanprover-community-bot-assistant' ]
        then
          printf $'bot=true\n'
          printf $'bot=true\n' >> "${GITHUB_OUTPUT}"
        else
          printf $'bot=false\n'
          printf $'bot=false\n' >> "${GITHUB_OUTPUT}"
        fi

    - id: user_permission
      if: ${{ inputs.mode == 'fix' && steps.bot_fix_style.outputs.bot_fix_style == 'bot-fix-style' }}
      uses: actions-cool/check-user-permission@7b90a27f92f3961b368376107661682c441f6103 # v2.3.0
      with:
        require: 'write'

    # from now on, it is sufficient to just check `user_permission`:
    # if the comment did not contain `bot fix style`,
    # then `user_permission` would not have ran
    - name: Add reaction (comment)
      # reactions are only supported for `comment`s and `review_comment`s?
      # This action only runs on `comment`s rather than `review`s or `review_comment`s
      # Is the `id` check a good way to check that this is a `comment`?
      if: ${{ inputs.mode == 'fix' && steps.user_permission.outputs.require-result == 'true' &&
              ! github.event.comment.id == '' }}
      uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
      with:
        comment-id: ${{ github.event.comment.id }}
        reactions: rocket

    - name: Add reaction (review comment)
      # this action only runs on `review_comment`s
      # is the `id` check a good way to check that this is a `review_comment`?
      if: ${{ inputs.mode == 'fix' && steps.user_permission.outputs.require-result == 'true' &&
              ! github.event.pull_request_review_comment.id == '' }}
      run: |
          gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls/comments/${{ github.event.comment.id }}/reactions \
            -f "content=rocket"
      env:
          GH_TOKEN: ${{ secrets.BOT_FIX_STYLE_TOKEN }}

    - name: cleanup
      if: ${{ inputs.mode == 'suggest' || steps.user_permission.outputs.require-result == 'true' }}
      run: |
        find . -name . -o -prune -exec rm -rf -- {} +

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      if: ${{ inputs.mode == 'suggest' || steps.user_permission.outputs.require-result == 'true' }}
      with:
        token: ${{ secrets.BOT_FIX_STYLE_TOKEN }}

    - name: Checkout PR branch
      if: ${{ inputs.mode == 'suggest' || steps.user_permission.outputs.require-result == 'true' }}
      run: |
          # covers `comment`s
          gh pr checkout ${{ github.event.issue.number }} ||
          # covers `review`s and `review_comment`s
          gh pr checkout ${{ github.event.pull_request.number }}
      env:
          GH_TOKEN: ${{ secrets.BOT_FIX_STYLE_TOKEN }}

    - name: install Python
      if: ${{ inputs.mode == 'suggest' || steps.user_permission.outputs.require-result == 'true' }}
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: 3.8

    - name: Configure Lean
      if: ${{ inputs.mode == 'suggest' || steps.user_permission.outputs.require-result == 'true' }}
      uses: leanprover/lean-action@e18f2df7f0d4f30d11a4b963bff9b1140999480c # 2025-04-22
      with:
        auto-config: false
        use-github-cache: false
        use-mathlib-cache: false

    - name: lint
      if: ${{ inputs.mode == 'suggest' || steps.user_permission.outputs.require-result == 'true' }}
      run: |
        lake exe lint-style --fix

    - name: suggester / lint-style
      if: ${{ inputs.mode == 'suggest' }}
      uses: reviewdog/action-suggester@4747dbc9f9e37adba0943e681cc20db466642158 # v1.21.0
      with:
        tool_name: lint-style (comment with "bot fix style" to have the bot commit all style suggestions)

    - name: Install bibtool
      if: ${{ inputs.mode == 'suggest' || steps.user_permission.outputs.require-result == 'true' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y bibtool

    - name: lint references.bib
      if: ${{ inputs.mode == 'suggest' || steps.user_permission.outputs.require-result == 'true' }}
      run: |
        # ignoring the return code allows the following `reviewdog` step to add GitHub suggestions
        ./scripts/lint-bib.sh || true

    - name: suggester / lint-bib
      if: ${{ inputs.mode == 'suggest' }}
      uses: reviewdog/action-suggester@4747dbc9f9e37adba0943e681cc20db466642158 # v1.21.0
      with:
        tool_name: lint-bib (comment with "bot fix style" to have the bot commit all style suggestions)

    - name: update {Mathlib, Tactic, Counterexamples, Archive}.lean
      if: ${{ inputs.mode == 'suggest' || steps.user_permission.outputs.require-result == 'true' }}
      run: |
        # ignoring the return code allows the following `reviewdog` step to add GitHub suggestions
        lake exe mk_all || true

    - name: suggester / import list
      if: ${{ inputs.mode == 'suggest' }}
      uses: reviewdog/action-suggester@4747dbc9f9e37adba0943e681cc20db466642158 # v1.21.0
      with:
        tool_name: imports (comment with "bot fix style" to have the bot commit all style suggestions)

    - name: Commit and push changes
      if: steps.user_permission.outputs.require-result == 'true'
      run: |
        # cleanup junk from build
        rm docs/references.bib.old
        # setup commit and push
        git config user.name "leanprover-community-mathlib4-bot"
        git config user.email "leanprover-community-mathlib4-bot@users.noreply.github.com"
        git add .
        # Don't fail if there's nothing to commit
        git commit -m "commit changes from style linters" || true
        git push origin HEAD
